//
// This file generated by rdl 1.4.12
//

package main

import (
	"fmt"
	"os"

	hello "../.."
)

func main() {
	endpoint := "localhost:4080"
	url := "http://" + endpoint + "/hello/v1"
	client := hello.NewClient(url, nil)
	name := os.Getenv("USER")
	greeting, err := client.GetGreeting(name)
	if err != nil {
		fmt.Println("***", err)
	} else {
		fmt.Println(greeting.Message)
	}
}
