//
// This file generated by rdl 1.5.0
//

package hello

import (
	"log"

	rdl "github.com/ardielle/ardielle-go/rdl"
)

var schema *rdl.Schema

func init() {
	sb := rdl.NewSchemaBuilder("hello")
	sb.Version(1)

	tGreeting := rdl.NewStructTypeBuilder("Struct", "Greeting")
	tGreeting.Field("message", "String", false, nil, "")
	sb.AddType(tGreeting.Build())

	mGetGreeting := rdl.NewResourceBuilder("Greeting", "GET", "/greeting")
	mGetGreeting.Input("name", "String", false, "sender", "", false, "human", "")
	sb.AddResource(mGetGreeting.Build())

	var err error
	schema, err = sb.BuildParanoid()
	if err != nil {
		log.Fatalf("rdl: schema build failed: %s", err)
	}
}

func HelloSchema() *rdl.Schema {
	return schema
}
