//
// This file generated by rdl 1.4.11
//
package hello

import (
	"fmt"

	rdl "github.com/ardielle/ardielle-go/rdl"
)

type HelloImpl struct{}

func (impl HelloImpl) GetGreeting(context *rdl.ResourceContext, name string) (*Greeting, error) {
	fmt.Printf("getGreeting(%v)\n", name)
	return &Greeting{Message: "Hello, " + name}, nil
}

//Authenticate - required by the framework. If returning true, you should set context.Principal to a valid object
func (impl *HelloImpl) Authenticate(context *rdl.ResourceContext) bool {
	fmt.Println("Authenticate")
	return false
}

//Authorize - required by the framework. Enforce authorization here.
func (impl *HelloImpl) Authorize(action string, resource string, principal rdl.Principal) (bool, error) {
	fmt.Printf("Authorize(%q, %q, %q", action, resource, principal.GetName())
	return true, nil
}
